apiVersion: v1
kind: Pod
metadata:
  name: pod-imagepullpolicy
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      imagePullPolicy: Never # 用于设置镜像拉取策略
    - name: busybox
      image: busybox:1.30
      imagePullPolicy: Always
# Always：总是从远程仓库拉取镜像（一直远程下载）
# IfNotPresent：本地有则使用本地镜像，本地没有则从远程仓库拉取镜像（本地有就本地 本地没远程下载）
# Never：只使用本地镜像，从不去远程仓库拉取，本地没有就报错 （一直使用本地）

# 默认值说明：
# 如果镜像tag为具体版本号， 默认策略是：IfNotPresent
# 如果镜像tag为：latest（最终版本） ，默认策略是always

# 创建Pod
# kubectl apply -f 002-pod-imagepullpolicy.yaml

# 查看Pod详情
# 此时明显可以看到nginx镜像没有一步Pulling image "nginx:1.17.1"的过程, 但 busybox 镜像有
# kubectl describe pod pod-imagepullpolicy -n dev

# 清理环境
# kubectl delete -f 002-pod-imagepullpolicy.yaml
