apiVersion: v1
kind: Pod
metadata:
  name: pod-ports
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      ports: # 设置容器暴露的端口列表
        - name: nginx-port
          containerPort: 80 # 如果代码没有监听，设置了也没用
          protocol: TCP
# 查看ports支持的子选项
# kubectl explain pod.spec.containers.ports
# KIND:     Pod
# VERSION:  v1
# RESOURCE: ports <[]Object>
# FIELDS:
#    name         <string>  # 端口名称，如果指定，必须保证name在pod中是唯一的
#    containerPort<integer> # 容器要监听的端口(0<x<65536)
#    hostPort     <integer> # 容器要在主机上公开的端口，如果设置，主机上只能运行容器的一个副本(一般省略)
#    hostIP       <string>  # 要将外部端口绑定到的主机IP(一般省略)
#    protocol     <string>  # 端口协议。必须是UDP、TCP或SCTP。默认为“TCP”。

# 创建Pod
# kubectl apply -f 005-pod-ports.yaml

# 查看pod
# 在下面可以明显看到配置信息
# kubectl get pod pod-ports -n dev -o yaml

# 清理环境
# kubectl delete -f 005-pod-ports.yaml
