apiVersion: v1
kind: Pod
metadata:
  name: pod-resources
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.17.1
      resources:
        limits:
          cpu: "2"
          memory: "20Gi"
        requests:
          cpu: "2"
          memory: "10Mi"
