apiVersion: v1
kind: Pod
metadata:
  name: hello-world-flask
spec:
  containers:
    - name: flask
      image: lyzhang1999/hello-world-flask:latest
      ports:
        - containerPort: 5000

# 安装 Kind 及 k8s
# go install sigs.k8s.io/kind@v0.20.0
# kind create cluster --config config.yaml

# 测试
# kubectl apply -f flask-pod.yaml
# kubectl port-forward pod/hello-world-flask 8000:5000
# curl 127.0.0.1:8000