apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: istio-loadbalance
  labels:
    app: server
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      containers:
        - name: server
          image: istio-loadbalance-server:v1

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: istio-loadbalance
spec:
  selector:
    app: server
  ports:
    - port: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server-virtualservice
spec:
  hosts:
    - server-service
  http:
    - name: server-service-route
      route:
        - destination:
            host: server-service
            subset: v1
#         weight: 90
          weight: 100
#       - destination:
#           host: server-service
#           subset: v2
#         weight: 10

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: server-destinationrule
spec:
  host: server-service
  trafficPolicy: # 指定默认的策略, 比如有 v1 和 v2两个版本, v2 版本没有指定的话就用这个
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: v1
      labels:
        version: v1
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
#    - name: v2
#      labels:
#        version: v2
#      trafficPolicy:
#        loadBalancer:
#          simple: ROUND_ROBIN