apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: dns-resolver
  labels:
    app: client
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: dns-resolver-client:v1